# Generated by Django 5.0.6 on 2026-07-14 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Caption / body text shown with the ad.')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='ads/')),
                ('button_text', models.CharField(blank=True, default='Learn more', max_length=64)),
                ('button_url', models.URLField(blank=True, null=True)),
                ('placement', models.CharField(choices=[('on_start', 'On /start'), ('before_video', 'Before sending video'), ('every_n_downloads', 'Every N downloads')], default='before_video', max_length=20)),
                ('frequency', models.PositiveIntegerField(default=5, help_text='Used with placement=every_n_downloads: show every N downloads.')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
