# Generated by Django 5.0.6 on 2026-07-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(blank=True, help_text='Public channel @username, without the @ (leave blank for private channels).', max_length=100, null=True)),
                ('chat_id', models.BigIntegerField(blank=True, help_text='Telegram chat_id, required for private channels so the bot can check membership via getChatMember.', null=True)),
                ('invite_link', models.URLField(help_text="Link shown to the user as the 'Subscribe' button.")),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
