# Generated by Django 5.0.6 on 2026-07-14 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('url', models.URLField(max_length=1000)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('recognizing', 'Recognizing audio'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='users.botuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found', models.BooleanField(default=False)),
                ('song_name', models.CharField(blank=True, max_length=300, null=True)),
                ('artist', models.CharField(blank=True, max_length=300, null=True)),
                ('album', models.CharField(blank=True, max_length=300, null=True)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('spotify_url', models.URLField(blank=True, null=True)),
                ('apple_music_url', models.URLField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recognition', to='downloads.videodownload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='videodownload',
            index=models.Index(fields=['platform'], name='downloads_v_platfor_278946_idx'),
        ),
        migrations.AddIndex(
            model_name='videodownload',
            index=models.Index(fields=['status'], name='downloads_v_status_8df8bc_idx'),
        ),
        migrations.AddIndex(
            model_name='videodownload',
            index=models.Index(fields=['created_at'], name='downloads_v_created_94473b_idx'),
        ),
    ]
